apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: blog-app   # 👈 IMPORTANT
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
      - name: blog-service
        image: ritiverma/reactproject-blog-service:latest
        ports:
        - containerPort: 8001
        env:
        - DB_HOST=blog-db
        - DB_PORT=5432
        - DB_USER=postgres
        - DB_PASSWORD=postgres
        - DB_NAME=blogs_golen

volumeMounts:
- name: upload-storage
  mountPath: /app/uploads

volumes:
- name: upload-storage
  persistentVolumeClaim:
    claimName: upload-pvc