apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-app   # 👈 IMPORTANT
spec:
  type: NodePort
  selector:
    app: blog-service
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001