apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-pvc
  namespace: blog-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  namespace: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: user-db
        image: postgres:15
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: users_golen
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: user-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  namespace: blog-app
spec:
  selector:
    app: user-db
  ports:
    - port: 5432
      targetPort: 5432